secretsanta/urls.py
from django.conf.urls import url

from . import views

app_name = 'secretsanta'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details', views.details, name='details'),
    url(r'^check_person/(?P<person_id>[0-9]+)$', views.check_person, name='check_person'),
    url(r'^rematch/(?P<match_id>[0-9]+)$', views.rematch, name='rematch'),
]

wrecksanta/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^secretsanta/', include('secretsanta.urls')),
    url(r'^admin/', admin.site.urls),
]

secretsanta/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=30)
    secret_key = models.CharField(max_length=6, null=True, blank=True)

    def __str__(self):
        return self.name


class Match(models.Model):
    gifter = models.ForeignKey(Person, db_column='gifter_id', related_name='+')
    giftee = models.ForeignKey(Person, db_column='giftee_id', related_name='+')

    def __str__(self):
        return self.gifter.name + " :: " + self.giftee.name

secretsanta/forms.py
from django import forms
from .models import Person

secretsanta/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from .models import Person, Match
import json
import random


# Create your views here.
def index(request):
    persons = Person.objects.all().order_by('name')
    return render(request, 'secretsanta/index.html', {'persons': persons})


def details(request):
    if request.method == 'POST':
        person_id = request.POST['person']

        # check for an existing match
        match = Match.objects.filter(gifter_id=person_id)

        if len(match) == 0:
            matched = [match.giftee_id for match in Match.objects.all()] + [person_id]
            people_remaining = Person.objects.exclude(id__in=matched)

            if len(people_remaining) != 0:
                matched_person = random.choice(people_remaining)
                secret_key = ''.join(random.choice('0123456789ACBDEF') for i in range(6))

                person = Person.objects.get(id=person_id)
                person.secret_key = secret_key

                person.save()

                match = Match.objects.create(gifter=person, giftee=matched_person)
                match.save()

                return render(request, 'secretsanta/details.html', {'match': match, 'can_rematch': True})
            else:
                return HttpResponse(404)
        else:  # check the incoming secret key
            secret_key = request.POST['secret_key']

            try:
                person = Person.objects.get(id=person_id, secret_key=secret_key)
            except ObjectDoesNotExist:
                person = None

            if person is None:
                messages.error(request, 'Incorrect secret key')
                return render(request, 'secretsanta/index.html', {'persons': Person.objects.all()})
            else:
                match = Match.objects.get(gifter=person)

            return render(request, 'secretsanta/details.html', {'match': match, 'can_rematch': False})
    else:
        return HttpResponse(404)

    return HttpResponse(404)


def rematch(request, match_id):
    match = Match.objects.get(id=match_id)
    gifter = Person.objects.get(id=match.gifter.id)
    gifter.secret_key = None

    match.delete()
    gifter.save()

    return redirect('/secretsanta')


def check_person(request, person_id):
    response_data = {'found': False}

    try:
        person = Person.objects.get(id=person_id)
    except ObjectDoesNotExist:
        person = None

    if person is not None:
        response_data['found'] = person.secret_key is not None and person.secret_key != ""

    return HttpResponse(json.dumps(response_data), content_type='application/json')

secretsanta/templates/secretsanta/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Secret Santa</title>
    <link rel="stylesheet" href="{% static 'secretsanta/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'secretsanta/css/base.css' %}"/>
    <script type="text/javascript" src="{% static 'secretsanta/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'secretsanta/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'secretsanta/js/site.js' %}"></script>
</head>
<body>
<div class="container-fluid" style="margin-top: 15px;">
    {% block main %}
    {% endblock %}
</div>
</body>
</html>

secretsanta/templates/secretsanta/details.html
{% extends "secretsanta/base.html" %}
{% block main %}
    <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Your Match</h3></div>
                <div class="panel-body">{{ match.giftee }}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Your Secret Key</h3></div>
                <div class="panel-body">{{ match.gifter.secret_key }}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-sm-offset-4 col-sm-1">
            <form action="{% url 'secretsanta:index' %}" action="get">
                <button class="btn btn-default" type="submit">Go Back</button>
            </form>
        </div>
        {% if can_rematch %}
            <div class="col-sm-1">
                <form class="form-horizontal" action="{% url 'secretsanta:rematch' match.id %}" action="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Rematch</button>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

secretsanta/templates/secretsanta/index.html
{% extends 'secretsanta/base.html' %}

{% block main %}
    <form class="form-horizontal" action="{% url 'secretsanta:details' %}" method="post">
        {% csrf_token %}
        {% if messages %}
            <div class="form-group">
                {% for message in messages %}
                    <div class="col-sm-12 error">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label class="col-sm-2 control-label">Who are you?</label>
            <div class="col-sm-2">
                <select id="person" name="person" class="form-control">
                    <option>-----</option>
                    {% for person in persons %}
                        <option value="{{ person.id }}">{{ person.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group" id="sec" style="display: none;">
            <label class="col-sm-2 control-label">Enter your secret key:</label>
            <div class="col-sm-3">
                <input type="text" name="secret_key" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2">
                <button class="btn btn-default" type="submit">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}